version: "3.9"
services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/client/node_modules
  backend:
    build:
      context: ./server
    ports:
      - "8080:8080"
    container_name: backend
    volumes:
      - ./server:/usr/src/app/server

